### ISSUE TITLE
Does not work with Blender 2.74

### ISSUE THREAD

**Issue by DimitriyPS** [ousttrue/pymeshio#19]
blender26-meshio - does not work with Blender 2.74. Can who be to actualize it?

**Comment by DimitriyPS** [comment]
![1](https://cloud.githubusercontent.com/assets/11189223/7040994/c1bf790e-dddd-11e4-8419-1c3ce2619e4d.png)

**Comment by ousttrue** [comment]
Thank you very much for your report. I'll check it later.

**Comment by meta-androcto** [comment]
hi, maybe check some of my hacks here:
I have 90% +  success import pmd
https://github.com/meta-androcto/blenderpython/tree/master/scripts/addons_extern/blender26-meshio
very simple fix but works.

**Comment by ousttrue** [comment]
It was no problem if I try (Windows8.1, Blender2.74(64bit), [pymeshio-2.78](https://pypi.python.org/pypi/pymeshio/).
You are perfectly copy all of the files ?

```
${blender directory}/2.6x/scripts/addons/
  +- blender26-meshio
       +- exporter
       +- pymeshio
```

**Comment by DimitriyPS** [comment]
Don't understand. Obviously it's my fault. If my memory is correct I downloaded the archive with the script from GitHub. But in this archive is different directory structure. Uploaded on your link - everything works.

ousttrue - I'm sorry to trouble you. Thank you very much.
