### ISSUE TITLE
[Question] What's triggering the bug in the screenshot?

### ISSUE THREAD

**Issue by ShadowKyogre** [ousttrue/pymeshio#20]
Hey there. One of my friends uses quite a lot. I can't seem to figure out what's causing the error in this screenshot:
![unknown_vertex_key_273_to_268](https://cloud.githubusercontent.com/assets/673620/7302677/e0b5af90-e99f-11e4-939c-3985f7fcdef1.jpeg)

---

For comparison:
http://www.mediafire.com/download/6jhk5mwp8x3vkbz/EXPORT+TEST.rar - To get the texture on the model to show:

1. Go to the material in PMD editor
2. Click the sky blue button in the texture notes box
3. Load texture

There're some other bugs that the model triggers, but that's probably best for another issue.

---

http://www.mediafire.com/download/8hwzoyyr8acswya/Miku+Original.rar - This is the model that causes the crash of the plugin.

---

The testing environment that my friend rar'd up to help make the problem reproducible (it uses 2.7.8 of the plugin, but the 2.7.9 changes on github don't address any of the PMD/PMX exporting issues:

* http://www.mediafire.com/download/nj5ozz1ti3ilvbq/PMD.rar <- the version of MMD in here is 64bit
* http://www.mediafire.com/download/m99s6sh82s3b9qn/MMD+BLENDER.rar

**Comment by ousttrue** [comment]
I have confirmed the problem .
First aid was as follows .

vertexarray.py
```
    def getMappedIndex(self, obj_name, base_index):
        key=VertexKey(self.objectMap[obj_name], base_index)
        if key in self.vertexMap:
            return self.vertexMap[key]
        return {}
```

I will release a modified version later .

**Comment by ousttrue** [comment]
upload 2.7.10

https://pypi.python.org/pypi/pymeshio
