### ISSUE TITLE
Japanese fonts not enabled in Blender

### ISSUE THREAD

**Issue by Hogarth-MMD** [ousttrue/pymeshio#30]
With these 2 lines of Python code, Japanese fonts can be automatically enabled in Blender when someone imports a .pmd or .pmx model.
Googleが翻訳します：
誰かが.pmdまたは.pmxモデルをインポートするときにPythonコードのこれらの2行で、日本語フォントは自動的にブレンダーで有効にすることができます。

import bpy

    bpy.context.user_preferences.system.use_international_fonts = True
    bpy.context.user_preferences.system.language = 'ja_JP'

**Comment by ousttrue** [comment]
Thank you !
