### ISSUE TITLE
'unknown deform' error

### ISSUE THREAD

**Issue by Hogarth-MMD** [ousttrue/pymeshio#31]
Seemingly pymeshio is unable to import a .pmx model if that model has 1 or more SDEF vertices. The result is "unknown deform" error. SDEF = spherical deform interpolation. I am almost 100% sure that Blender does not support SDEF rigging. And it is impossible or impractical to attach custom properties to vertices. The custom properties data would become disorganized or destroyed after someone deletes or adds vertices in Blender.

My suggested bug fix:

Import all SDEF vertices as BDEF2 vertices and re-export them as BDEF2 vertices. Wait until a future version of Blender is released which supports SDEF. Then make a new and better bug fix.

Googleが翻訳します：
そのモデルは、1以上のSDEF頂点を持っている場合、一見pymeshio .pmxモデルをインポートすることができません。結果は「不明な変形」エラーです。 SDEF =球状変形補間。私はBlenderがSDEF談合をサポートしていないことがほぼ100％確信しています。そして、それは頂点にカスタムプロパティをアタッチすることが不可能または非現実的です。誰かが削除またはBlenderの頂点を追加した後、カスタムプロパティデータが無秩序または破壊になります。

私の提案のバグ修正：

BDEF2頂点としてすべてSDEF頂点をインポートし、BDEF2頂点としてそれらを再エクスポートします。ブレンダーの将来のバージョンがSDEFをサポートするリリースされるまで待ちます。次に、新しい、より良いバグ修正を行います。

**Comment by ousttrue** [comment]
Thank you !
