### ISSUE TITLE
no import of UV morphs, material morphs, group morphs, bone pose morphs of .pmx model

### ISSUE THREAD

**Issue by Hogarth-MMD** [ousttrue/pymeshio#32]
Pymeshio cannot import any material morphs, UV morphs, bone pose morphs, or group morphs of a .pmx model. If a .pmx model has a UV morph or group morph or bone pose morph, the import is interrupted by an error message.

My suggested bug fix:

Import all of the data of material morphs, UV morphs, bone pose morphs, and group morphs into custom properties. When the .pmx model is re-exported from Blender, this data will be retrieved from the custom properties and these morphs will be re-exported with the .pmx model.

Googleが翻訳します：
Pymeshioは任意の材料モーフ、UVモーフ、骨をインポートすることはできませんモーフ、または.pmxモデルのグループモーフをもたらします。 .pmxモデルはUVモーフまたはグループモーフや骨がモーフを提起した場合、インポートはエラーメッセージによって中断されています。

私の提案のバグ修正：

材料モーフ、UVモーフのすべてのデータをインポートし、骨はモーフを提起し、グループがカスタムプロパティにモーフィング。 .pmxモデルは、ブレンダーから再輸出された場合、このデータはカスタムプロパティから取得され、これらのモーフは.pmxモデルで再エクスポートされます。

**Comment by ousttrue** [comment]
Thank you !
It was repaired so as not to cause exception.
